#pragma once
#include <QObject>
#include <QDBusContext>
#include <QString>
#include <QVariantMap>

// Adaptor will be auto-generated by qdbusxml2cpp from the introspection XML.
// This class IS the D-Bus interface implementation.

/**
 * @class SystemInfoService
 * @brief D-Bus service object exposing basic host system information.
 *
 * Registered on the session bus as `ru.perfilyev.SystemInfo`. Every public
 * slot below is exposed as a D-Bus method (see Q_CLASSINFO). A periodic
 * timer emits StatsUpdated() with fresh memory stats every kStatsIntervalMs.
 */
class SystemInfoService : public QObject, protected QDBusContext {
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ru.perfilyev.SystemInfo")

public:
    explicit SystemInfoService(QObject* parent = nullptr);

public slots:  // All public slots are exposed as D-Bus methods
    [[nodiscard]] QString     GetHostname() const;
    [[nodiscard]] QVariantMap GetMemoryInfo() const;
    [[nodiscard]] int         GetCpuCount() const;
    [[nodiscard]] QString     GetUptime() const;
    [[nodiscard]] QString     Echo(const QString& message) const;

signals:
    // D-Bus signal — emitted when "stats changed"
    void StatsUpdated(const QString& info);

};
