#pragma once
#include <QObject>
#include <QDBusContext>
#include <QString>
#include <QVariantMap>

// Adaptor will be auto-generated by qdbusxml2cpp from the introspection XML.
// This class IS the D-Bus interface implementation.

class SystemInfoService : public QObject, protected QDBusContext {
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ru.perfilyev.SystemInfo")

public:
    explicit SystemInfoService(QObject* parent = nullptr);

public slots:  // All public slots are exposed as D-Bus methods
    QString     GetHostname() const;
    QVariantMap GetMemoryInfo() const;
    int         GetCpuCount() const;
    QString     GetUptime() const;
    QString     Echo(const QString& message) const;

signals:
    // D-Bus signal — emitted when "stats changed"
    void StatsUpdated(const QString& info);

};
